export type CountryDial = {
  name: string;
  iso: string;
  dial: string;
};

/** Sorted A–Z by country name. Default for CR forms: Costa Rica. */
export const countryDials: CountryDial[] = [
  { name: "Afganistán", iso: "AF", dial: "+93" },
  { name: "Albania", iso: "AL", dial: "+355" },
  { name: "Alemania", iso: "DE", dial: "+49" },
  { name: "Andorra", iso: "AD", dial: "+376" },
  { name: "Angola", iso: "AO", dial: "+244" },
  { name: "Anguila", iso: "AI", dial: "+1264" },
  { name: "Antigua y Barbuda", iso: "AG", dial: "+1268" },
  { name: "Arabia Saudita", iso: "SA", dial: "+966" },
  { name: "Argelia", iso: "DZ", dial: "+213" },
  { name: "Argentina", iso: "AR", dial: "+54" },
  { name: "Armenia", iso: "AM", dial: "+374" },
  { name: "Aruba", iso: "AW", dial: "+297" },
  { name: "Australia", iso: "AU", dial: "+61" },
  { name: "Austria", iso: "AT", dial: "+43" },
  { name: "Azerbaiyán", iso: "AZ", dial: "+994" },
  { name: "Bahamas", iso: "BS", dial: "+1242" },
  { name: "Bangladés", iso: "BD", dial: "+880" },
  { name: "Barbados", iso: "BB", dial: "+1246" },
  { name: "Baréin", iso: "BH", dial: "+973" },
  { name: "Bélgica", iso: "BE", dial: "+32" },
  { name: "Belice", iso: "BZ", dial: "+501" },
  { name: "Benín", iso: "BJ", dial: "+229" },
  { name: "Bielorrusia", iso: "BY", dial: "+375" },
  { name: "Bolivia", iso: "BO", dial: "+591" },
  { name: "Bosnia y Herzegovina", iso: "BA", dial: "+387" },
  { name: "Botsuana", iso: "BW", dial: "+267" },
  { name: "Brasil", iso: "BR", dial: "+55" },
  { name: "Brunéi", iso: "BN", dial: "+673" },
  { name: "Bulgaria", iso: "BG", dial: "+359" },
  { name: "Burkina Faso", iso: "BF", dial: "+226" },
  { name: "Burundi", iso: "BI", dial: "+257" },
  { name: "Bután", iso: "BT", dial: "+975" },
  { name: "Cabo Verde", iso: "CV", dial: "+238" },
  { name: "Camboya", iso: "KH", dial: "+855" },
  { name: "Camerún", iso: "CM", dial: "+237" },
  { name: "Canadá", iso: "CA", dial: "+1" },
  { name: "Catar", iso: "QA", dial: "+974" },
  { name: "Chad", iso: "TD", dial: "+235" },
  { name: "Chile", iso: "CL", dial: "+56" },
  { name: "China", iso: "CN", dial: "+86" },
  { name: "Chipre", iso: "CY", dial: "+357" },
  { name: "Colombia", iso: "CO", dial: "+57" },
  { name: "Comoras", iso: "KM", dial: "+269" },
  { name: "Congo", iso: "CG", dial: "+242" },
  { name: "Congo (RDC)", iso: "CD", dial: "+243" },
  { name: "Corea del Norte", iso: "KP", dial: "+850" },
  { name: "Corea del Sur", iso: "KR", dial: "+82" },
  { name: "Costa Rica", iso: "CR", dial: "+506" },
  { name: "Côte d'Ivoire", iso: "CI", dial: "+225" },
  { name: "Croacia", iso: "HR", dial: "+385" },
  { name: "Cuba", iso: "CU", dial: "+53" },
  { name: "Curazao", iso: "CW", dial: "+599" },
  { name: "Dinamarca", iso: "DK", dial: "+45" },
  { name: "Dominica", iso: "DM", dial: "+1767" },
  { name: "Ecuador", iso: "EC", dial: "+593" },
  { name: "Egipto", iso: "EG", dial: "+20" },
  { name: "El Salvador", iso: "SV", dial: "+503" },
  { name: "Emiratos Árabes Unidos", iso: "AE", dial: "+971" },
  { name: "Eritrea", iso: "ER", dial: "+291" },
  { name: "Eslovaquia", iso: "SK", dial: "+421" },
  { name: "Eslovenia", iso: "SI", dial: "+386" },
  { name: "España", iso: "ES", dial: "+34" },
  { name: "Estados Unidos", iso: "US", dial: "+1" },
  { name: "Estonia", iso: "EE", dial: "+372" },
  { name: "Esuatini", iso: "SZ", dial: "+268" },
  { name: "Etiopía", iso: "ET", dial: "+251" },
  { name: "Filipinas", iso: "PH", dial: "+63" },
  { name: "Finlandia", iso: "FI", dial: "+358" },
  { name: "Fiyi", iso: "FJ", dial: "+679" },
  { name: "Francia", iso: "FR", dial: "+33" },
  { name: "Gabón", iso: "GA", dial: "+241" },
  { name: "Gambia", iso: "GM", dial: "+220" },
  { name: "Georgia", iso: "GE", dial: "+995" },
  { name: "Ghana", iso: "GH", dial: "+233" },
  { name: "Gibraltar", iso: "GI", dial: "+350" },
  { name: "Granada", iso: "GD", dial: "+1473" },
  { name: "Grecia", iso: "GR", dial: "+30" },
  { name: "Groenlandia", iso: "GL", dial: "+299" },
  { name: "Guadalupe", iso: "GP", dial: "+590" },
  { name: "Guam", iso: "GU", dial: "+1671" },
  { name: "Guatemala", iso: "GT", dial: "+502" },
  { name: "Guayana Francesa", iso: "GF", dial: "+594" },
  { name: "Guernsey", iso: "GG", dial: "+44" },
  { name: "Guinea", iso: "GN", dial: "+224" },
  { name: "Guinea Ecuatorial", iso: "GQ", dial: "+240" },
  { name: "Guinea-Bisáu", iso: "GW", dial: "+245" },
  { name: "Guyana", iso: "GY", dial: "+592" },
  { name: "Haití", iso: "HT", dial: "+509" },
  { name: "Honduras", iso: "HN", dial: "+504" },
  { name: "Hong Kong", iso: "HK", dial: "+852" },
  { name: "Hungría", iso: "HU", dial: "+36" },
  { name: "India", iso: "IN", dial: "+91" },
  { name: "Indonesia", iso: "ID", dial: "+62" },
  { name: "Irak", iso: "IQ", dial: "+964" },
  { name: "Irán", iso: "IR", dial: "+98" },
  { name: "Irlanda", iso: "IE", dial: "+353" },
  { name: "Isla de Man", iso: "IM", dial: "+44" },
  { name: "Islandia", iso: "IS", dial: "+354" },
  { name: "Islas Caimán", iso: "KY", dial: "+1345" },
  { name: "Islas Cook", iso: "CK", dial: "+682" },
  { name: "Islas Feroe", iso: "FO", dial: "+298" },
  { name: "Islas Malvinas", iso: "FK", dial: "+500" },
  { name: "Islas Marshall", iso: "MH", dial: "+692" },
  { name: "Islas Salomón", iso: "SB", dial: "+677" },
  { name: "Islas Turcas y Caicos", iso: "TC", dial: "+1649" },
  { name: "Islas Vírgenes Británicas", iso: "VG", dial: "+1284" },
  { name: "Islas Vírgenes de EE. UU.", iso: "VI", dial: "+1340" },
  { name: "Israel", iso: "IL", dial: "+972" },
  { name: "Italia", iso: "IT", dial: "+39" },
  { name: "Jamaica", iso: "JM", dial: "+1876" },
  { name: "Japón", iso: "JP", dial: "+81" },
  { name: "Jersey", iso: "JE", dial: "+44" },
  { name: "Jordania", iso: "JO", dial: "+962" },
  { name: "Kazajistán", iso: "KZ", dial: "+7" },
  { name: "Kenia", iso: "KE", dial: "+254" },
  { name: "Kirguistán", iso: "KG", dial: "+996" },
  { name: "Kiribati", iso: "KI", dial: "+686" },
  { name: "Kuwait", iso: "KW", dial: "+965" },
  { name: "Laos", iso: "LA", dial: "+856" },
  { name: "Lesoto", iso: "LS", dial: "+266" },
  { name: "Letonia", iso: "LV", dial: "+371" },
  { name: "Líbano", iso: "LB", dial: "+961" },
  { name: "Liberia", iso: "LR", dial: "+231" },
  { name: "Libia", iso: "LY", dial: "+218" },
  { name: "Liechtenstein", iso: "LI", dial: "+423" },
  { name: "Lituania", iso: "LT", dial: "+370" },
  { name: "Luxemburgo", iso: "LU", dial: "+352" },
  { name: "Macao", iso: "MO", dial: "+853" },
  { name: "Macedonia del Norte", iso: "MK", dial: "+389" },
  { name: "Madagascar", iso: "MG", dial: "+261" },
  { name: "Malasia", iso: "MY", dial: "+60" },
  { name: "Malaui", iso: "MW", dial: "+265" },
  { name: "Maldivas", iso: "MV", dial: "+960" },
  { name: "Malí", iso: "ML", dial: "+223" },
  { name: "Malta", iso: "MT", dial: "+356" },
  { name: "Marruecos", iso: "MA", dial: "+212" },
  { name: "Martinica", iso: "MQ", dial: "+596" },
  { name: "Mauricio", iso: "MU", dial: "+230" },
  { name: "Mauritania", iso: "MR", dial: "+222" },
  { name: "México", iso: "MX", dial: "+52" },
  { name: "Micronesia", iso: "FM", dial: "+691" },
  { name: "Moldavia", iso: "MD", dial: "+373" },
  { name: "Mónaco", iso: "MC", dial: "+377" },
  { name: "Mongolia", iso: "MN", dial: "+976" },
  { name: "Montenegro", iso: "ME", dial: "+382" },
  { name: "Montserrat", iso: "MS", dial: "+1664" },
  { name: "Mozambique", iso: "MZ", dial: "+258" },
  { name: "Myanmar", iso: "MM", dial: "+95" },
  { name: "Namibia", iso: "NA", dial: "+264" },
  { name: "Nauru", iso: "NR", dial: "+674" },
  { name: "Nepal", iso: "NP", dial: "+977" },
  { name: "Nicaragua", iso: "NI", dial: "+505" },
  { name: "Níger", iso: "NE", dial: "+227" },
  { name: "Nigeria", iso: "NG", dial: "+234" },
  { name: "Niue", iso: "NU", dial: "+683" },
  { name: "Noruega", iso: "NO", dial: "+47" },
  { name: "Nueva Caledonia", iso: "NC", dial: "+687" },
  { name: "Nueva Zelanda", iso: "NZ", dial: "+64" },
  { name: "Omán", iso: "OM", dial: "+968" },
  { name: "Países Bajos", iso: "NL", dial: "+31" },
  { name: "Pakistán", iso: "PK", dial: "+92" },
  { name: "Palau", iso: "PW", dial: "+680" },
  { name: "Palestina", iso: "PS", dial: "+970" },
  { name: "Panamá", iso: "PA", dial: "+507" },
  { name: "Papúa Nueva Guinea", iso: "PG", dial: "+675" },
  { name: "Paraguay", iso: "PY", dial: "+595" },
  { name: "Perú", iso: "PE", dial: "+51" },
  { name: "Polinesia Francesa", iso: "PF", dial: "+689" },
  { name: "Polonia", iso: "PL", dial: "+48" },
  { name: "Portugal", iso: "PT", dial: "+351" },
  { name: "Puerto Rico", iso: "PR", dial: "+1" },
  { name: "Reino Unido", iso: "GB", dial: "+44" },
  { name: "República Centroafricana", iso: "CF", dial: "+236" },
  { name: "República Checa", iso: "CZ", dial: "+420" },
  { name: "República Dominicana", iso: "DO", dial: "+1" },
  { name: "Reunión", iso: "RE", dial: "+262" },
  { name: "Ruanda", iso: "RW", dial: "+250" },
  { name: "Rumania", iso: "RO", dial: "+40" },
  { name: "Rusia", iso: "RU", dial: "+7" },
  { name: "Samoa", iso: "WS", dial: "+685" },
  { name: "Samoa Americana", iso: "AS", dial: "+1684" },
  { name: "San Marino", iso: "SM", dial: "+378" },
  { name: "San Martín", iso: "MF", dial: "+590" },
  { name: "San Vicente y las Granadinas", iso: "VC", dial: "+1784" },
  { name: "Santa Lucía", iso: "LC", dial: "+1758" },
  { name: "Santo Tomé y Príncipe", iso: "ST", dial: "+239" },
  { name: "Senegal", iso: "SN", dial: "+221" },
  { name: "Serbia", iso: "RS", dial: "+381" },
  { name: "Seychelles", iso: "SC", dial: "+248" },
  { name: "Sierra Leona", iso: "SL", dial: "+232" },
  { name: "Singapur", iso: "SG", dial: "+65" },
  { name: "Sint Maarten", iso: "SX", dial: "+1721" },
  { name: "Siria", iso: "SY", dial: "+963" },
  { name: "Somalia", iso: "SO", dial: "+252" },
  { name: "Sri Lanka", iso: "LK", dial: "+94" },
  { name: "Sudáfrica", iso: "ZA", dial: "+27" },
  { name: "Sudán", iso: "SD", dial: "+249" },
  { name: "Sudán del Sur", iso: "SS", dial: "+211" },
  { name: "Suecia", iso: "SE", dial: "+46" },
  { name: "Suiza", iso: "CH", dial: "+41" },
  { name: "Surinam", iso: "SR", dial: "+597" },
  { name: "Tailandia", iso: "TH", dial: "+66" },
  { name: "Taiwán", iso: "TW", dial: "+886" },
  { name: "Tanzania", iso: "TZ", dial: "+255" },
  { name: "Tayikistán", iso: "TJ", dial: "+992" },
  { name: "Timor Oriental", iso: "TL", dial: "+670" },
  { name: "Togo", iso: "TG", dial: "+228" },
  { name: "Tonga", iso: "TO", dial: "+676" },
  { name: "Trinidad y Tobago", iso: "TT", dial: "+1868" },
  { name: "Túnez", iso: "TN", dial: "+216" },
  { name: "Turkmenistán", iso: "TM", dial: "+993" },
  { name: "Turquía", iso: "TR", dial: "+90" },
  { name: "Tuvalu", iso: "TV", dial: "+688" },
  { name: "Ucrania", iso: "UA", dial: "+380" },
  { name: "Uganda", iso: "UG", dial: "+256" },
  { name: "Uruguay", iso: "UY", dial: "+598" },
  { name: "Uzbekistán", iso: "UZ", dial: "+998" },
  { name: "Vanuatu", iso: "VU", dial: "+678" },
  { name: "Vaticano", iso: "VA", dial: "+39" },
  { name: "Venezuela", iso: "VE", dial: "+58" },
  { name: "Vietnam", iso: "VN", dial: "+84" },
  { name: "Wallis y Futuna", iso: "WF", dial: "+681" },
  { name: "Yemen", iso: "YE", dial: "+967" },
  { name: "Yibuti", iso: "DJ", dial: "+253" },
  { name: "Zambia", iso: "ZM", dial: "+260" },
  { name: "Zimbabue", iso: "ZW", dial: "+263" },
];

export const defaultCountryIso = "CR";
